version: '3.7'

services:
  nginx:
    image: nginx
    restart: "unless-stopped"
    networks:
      - mtltools
    depends_on:
      - php-api
      - node-app
    volumes:
      - ./:/var/www/api
      - ./resources/frontend:/home/node/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 888:80

  php-api:
    build:
      context: ./.docker/php
    restart: "unless-stopped"
    working_dir: /var/www/api
    env_file: .env
    entrypoint: composer install
    networks:
      - mtltools
    volumes:
      - ./:/var/www/api

  node-app:
    build:
      context: ./.docker/node
    restart: "unless-stopped"
    working_dir: /home/node/app
    entrypoint: bash -c "npm install && npm start"
    networks:
      - mtltools
    volumes:
      - ./resources/frontend:/home/node/app


networks:
  mtltools:
    name: mtltools
