version: '3.7'

services:
  nginx:
    image: nginx
    restart: "unless-stopped"
    networks:
      mtltools:
        ipv4_address: 192.168.66.66
    depends_on:
      - php-api
      - node-app
    volumes:
      - ./:/var/www/api
      - ./resources/frontend:/home/node/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 800:80

  php-api:
    build:
      context: ./.docker/php
    restart: "unless-stopped"
    working_dir: /var/www/api
    user: ${CURRENT_UID}
    env_file: .env
    networks:
      mtltools:
        ipv4_address: 192.168.66.67
    volumes:
      - ./:/var/www/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "api.mtltools.docker:192.168.66.66"
      - "mtltools.docker:192.168.66.66"

  node-app:
    build:
      context: ./.docker/node
    restart: "unless-stopped"
    working_dir: /home/node/app
    entrypoint: bash -c "npm install && npm run startDev"
    networks:
      mtltools:
        ipv4_address: 192.168.66.68
    volumes:
      - ./resources/frontend:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "api.mtltools.docker:192.168.66.66"
      - "mtltools.docker:192.168.66.66"

  db:
    image: mariadb
    restart: "unless-stopped"
    networks:
      - mtltools
    volumes:
      - /var/lib/mysql/
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MARIADB_DATABASE: db

  php-startup:
    build:
      context: ./.docker/php
    working_dir: /var/www/api
    user: ${CURRENT_UID}
    env_file: .env
    entrypoint: bash -c "composer install; php artisan migrate;"
    depends_on:
      - db
    networks:
      mtltools:
        ipv4_address: 192.168.66.57
    volumes:
      - ./:/var/www/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "api.mtltools.docker:192.168.66.66"
      - "mtltools.docker:192.168.66.66"


networks:
  mtltools:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.66.0/24
          gateway: 192.168.66.1
